##
## SonataClassificationBundle configuration
##            
#sonata_classification:
#    class:
#        tag:          Sfynx\ClassificationBundle\Entity\Tag
#        collection:   Sfynx\ClassificationBundle\Entity\Collection
#        context:      Sfynx\ClassificationBundle\Entity\Context
#        media:        Sfynx\MediaBundle\Entity\Media
#        category:     Sfynx\ClassificationBundle\Entity\Category
#
#    admin:
#        tag:
#            class:        Sonata\ClassificationBundle\Admin\TagAdmin
#            controller:   SonataAdminBundle:CRUD
#            translation:  SonataClassificationBundle
#        category:
#            class:        Sonata\ClassificationBundle\Admin\CategoryAdmin
#            controller:   SonataAdminBundle:CRUD
#            translation:  SonataClassificationBundle
#        collection:
#            class:        Sonata\ClassificationBundle\Admin\CollectionAdmin
#            controller:   SonataAdminBundle:CRUD
#            translation:  SonataClassificationBundle  
#
#